### ISSUE TITLE
Question: why is column tenant_tkey in bssuser.organization table not always updated?

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#396] opened 2016-10-21 13:49 UTC
[Version]
V16.2 

[Date]
2016/10/19

[Test category] 
Creative

[Description]
I was looking for the tenant ID of my customer organization. So i opened the bssuser.organization table and looked up the organizations.
To my surprise half of them did not have an tenant ID: see pic below
![image](https://cloud.githubusercontent.com/assets/19411047/19600125/dd30e3fe-97a3-11e6-9e37-197769031e70.png)

The organizations 'The real thing', 'From Hell' and 'MiniLuv' belong to the default tenant. Therefore the 
tenenat ID is empty. 

But: 'MiniPlenty' is a customer organisation of 'MiniPax' therefore they should have the same tenant ID: 10000
'DoubleThink' is an customer organisation of 'MiniTrue' and should have the tenant ID: 10001.

Is is confusing that some organization do not have the correct tenant id assigned here.

[Steps to reproduce]

[Expected result]

[Observed result] 

[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment] 2016-10-21 15:20
This is an issue which is the reason for the issue #389. There is difference in the implementation for customers registered by platform operator and supplier. 
Platform operator can choose the tenant and marketplace to associate with his customer organization. The chosen marketplace is one of the tenant-specific marketplaces. In this case the tenant key is written to the database.
In case supplier registers a customer organization, he has only possibility to choose the marketplace. The tenant is then implicitly known (the tenant of the chosen marketplace). This is not reflected in the organization table, the tenant key is missing for the customer organization in this case.

**Comment by StavrevaS** [comment] 2016-10-21 15:21
The issue is marked as duplicate to the issue #389

**Closed** 2016-10-21 16:31 UTC
Labels: bug/status/duplicate, foundby/ST, question
