### ISSUE TITLE
Jar not found exceptions

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/development#627] opened 2017-03-28 06:30 UTC
```
[2017-03-27T12:41:12.375+0200] [glassfish 4.1] [WARNING] [] [org.apache.jasper.runtime.TldScanner] [tid: _ThreadID=43 _ThreadName=admin-listener(4)] [timeMillis: 1490611272375] [levelValue: 900] [[
  PWC6351: In TLD scanning, the supplied resource file:/opt/glassfish-4.1.1/glassfish/domains/integration-bes/applications/oscm/lib/../modules/gf-client-module.jar does not exist
java.io.FileNotFoundException: /opt/glassfish-4.1.1/glassfish/domains/integration-bes/applications/oscm/lib/../modules/gf-client-module.jar (No such file or directory)
```

**Comment by GoebelL** [comment] 2017-03-31 10:04
Please check and comment if there are impacts.

**Comment by DawidCh** [comment] 2017-03-31 11:01
THe problem occurs sometimes and no impact has been found so far.

**Comment by GoebelL** [comment] 2017-03-31 12:57
As long as there is no impact it's minor.

**Comment by grubskim** [comment] 2017-04-04 13:16
Closing as duplicate of #592

**Closed by grubskim** 2017-04-04 13:16 UTC
Labels: feature-branch/fb_glassfish4_upgrade, priority/P2, severity/minor
