### ISSUE TITLE
hibernate sequences table is broken for app db (since 17.0)

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#696] opened 2017-05-11 10:45 UTC
[Version]
17.0 **2017/05/11**

[How to reproduce]
1. install 17.0
2. work with app by creating subscriptions to provisioning services e.g. aws/openstack

[Expected result]
hibernate sequences are generated correctly, no duplicate key problems

[Observed result]
duplicate key errors occur, no more operations possible in APP

[Details]
Before upgrade to 17.0, app hibernate_sequence table values:
ServiceInstance	86
InstanceAttribute	18
InstanceParameter	87
Operation	64

After working with 17.0, app hibernate_sequence table values:
ServiceInstance	2086
InstanceAttribute	2018
InstanceParameter	2087
Operation	64

My guess is that the incorrect value hibernate_sequence sequence_next_hi_value is stored.
In my case I added 2 subscriptions (aws) and got two new (bad) values for tkey values for serviceinstance
See attached file.

(Note: bes db is ok, hibernate_sequence table values for sequence_next_hi_value  are between 10 and 197)

**Comment by SylviaDehn** [comment] 2017-05-11 10:46
![serviceinstance](https://cloud.githubusercontent.com/assets/15086024/25945610/d73aeab0-3647-11e7-9bc6-604a57310fe6.jpg)

**Comment by StavrevaS** [comment] 2017-05-11 12:21
The id generator was changed from:
@SequenceGenerator(name = "do_seq", allocationSize = 1000)
to 
@TableGenerator(table = "hibernate_sequences", name = "do_seq", allocationSize = 1000, valueColumnName = "sequence_next_hi_value").

@DawidCh do you know the reason?

**Comment by DawidCh** [comment] 2017-05-12 07:11
Yes, it had to be changed because it didn't work properly. I can't remember the details now.

**Comment by SylviaDehn** [comment] 2017-05-15 06:51
@StavrevaS @DawidCh This bug is blocking me from testing with my DB. Please take care of it asap.

**Comment by GoebelL** [comment] 2017-05-15 08:01
I found there is a slight difference of persistence.xml hibernate configuration between  OSCM core and APP. Especially, I am concerned about the following property missing for APP persistence.xml.

 <property name="hibernate.id.new_generator_mappings" value="**false**"/>

Note that the default is **true** here.
Check also https://docs.jboss.org/author/display/WFLY8/JPA+Reference+Guide#JPAReferenceGuide-Hibernateproperties
"New applications should let this default to true, older applications with existing data might need to set to false (see note below).  It really depends on whether your application uses the @GeneratedValue(AUTO) which will generates new key values for newly created entities.  The application can override this value (in the persistence.xml)."

Maybe related?

**Comment by GoebelL** [comment] 2017-05-15 15:58
The issue is fixed by adding the mentioned property. Verification tests are in progress.

**Comment by GoebelL** [comment] 2017-05-15 15:58
As agreed, we will provide a hot fix release for this issue.

@gertipoppel 
The fix requires an update to the version numbers in the manuals - 17.0.1 and a short note about this issue in the release notes.

**Comment by DawidCh** [comment] 2017-05-16 06:52
[Details of fix]
Added property for app, which is mandatory to glassfish4 to get number generators to work properly:
hibernate.id.new_generator_mappings
The property has been set to bes domain but forgotten to set to app.

**Closed by DawidCh** 2017-05-16 06:52 UTC
Labels: bug/status/new, foundby/FT, priority/P1, severity/critical

**Comment by gertipoppel** [comment] 2017-05-16 09:50
Added the following to the Release Notes of V17.0.1 (What's New --> GlassFish 4.1.1 Application Server --> Update Installation of APP and/or Service Controllers):

GlassFish 4 requires a change to its default configuration so that numbers are generated correctly
(needed, for example, for the IDs of the search index). In the persistence.xml file, the following
property must be set to false instead of the default true:
<property name="hibernate.id.new_generator_mappings" value="false"/>

Adjusted the version number of the manuals to 17.0.1

**Comment by SylviaDehn** [comment] 2017-07-03 07:59
Verified with 17.1
