### ISSUE TITLE
app applications are not undeployed correctly in GF4 environment

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#763] opened 2017-06-14 10:53 UTC
[Version]
17.1 2017/06/02

[How to reproduce]
1. update app domain installation by 
- undeploy oscm-app
- undeploy oscm-app-aws (or any other controller application)
- redeploy the 2 above applications

[Expected result]
applications can be deployed

[Observed result]
error occurs at deploy.

[Details]
Problem here is that the undeploy does not remove everything from folder
C:\glassfish4\glassfish\domains\app\applications
oscm-app and oscm-app-aws folders still exist.
If you stop the domain, remove these directories manually, and then restart and then deploy, it works ok.
This is only a problem in the app domain. Not in the bes domain. The problem also did not exist in GF3.
This problem also exists in other environments, not just on my machine.

**Comment by DawidCh** [comment] 2017-06-23 12:05
I have a filling that this maybe the known issue:
https://github.com/javaee/glassfish/issues/21283
Could you please check?

**Comment by StavrevaS** [comment] 2017-06-30 07:24
I had the same problem during tests with VMware controller. By undeployment there are glassfish staled files: richfaces jars, and by vmware controller also the vmware jar file.
I agree with @DawidCh that it might be the issue already reported.
But please also check if this happens on Linux. Maybe is some Windows locking problem.

**Comment by SylviaDehn** [comment] 2017-07-04 11:09
@DawidCh I don't think this is the glassfish problem mentioned above. Possibly a file locking problem.

**Comment by DawidCh** [comment] 2017-07-11 06:17
Fix also #650

**Comment by badziakp** [comment] 2017-07-21 09:32
This problem is a glassfish issue which is reported on glassfish github. Changes in packaging of OSCM didn't solve the problem because the richfaces-4.5.0.jar could still be found in .glassfishStaleFiles. This problem shouldn't occure in linux environment but I didn't check it. I found out that the bug has been fixed in Payara Server 172 which bases on opensource version of glassfish. I installed Payara and checked it and this bug is fixed there. Applications can be redeployed without any problems. Is there any possibility that we will switch to Payara server?

**Comment by toshihiro-shiino** [comment] 2017-07-28 06:27
We confirmed to reproduce with v17.3.
```
    Directory: F:\FCSM\glassfish4\glassfish\domains\app-row-domain\applications\oscm-app-vmware


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/28/2017   6:17 AM                lib                                                                   
d-----        7/28/2017   6:17 AM                oscm-app-vmware-ui_war                                                
-a----        7/28/2017   6:17 AM            271 .glassfishStaleFiles                                                  


    Directory: F:\FCSM\glassfish4\glassfish\domains\app-row-domain\applications\oscm-app-vmware\lib


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
------        7/28/2017   6:11 AM         188545 oscm-app-vmware.jar                                                   


    Directory: F:\FCSM\glassfish4\glassfish\domains\app-row-domain\applications\oscm-app-vmware\oscm-app-vmware-ui_war


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/28/2017   6:17 AM                WEB-INF                                                               


    Directory: 
    F:\FCSM\glassfish4\glassfish\domains\app-row-domain\applications\oscm-app-vmware\oscm-app-vmware-ui_war\WEB-INF


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/28/2017   6:17 AM                lib                                                                   


    Directory: 
    F:\FCSM\glassfish4\glassfish\domains\app-row-domain\applications\oscm-app-vmware\oscm-app-vmware-ui_war\WEB-INF\lib


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
------        7/28/2017   6:11 AM        8634334 richfaces-components-rich-4.5.0.Final.jar                             
------        7/28/2017   6:11 AM        1354397 richfaces-core-4.5.0.Final.jar                                        
```

**Comment by SylviaDehn** [comment] 2017-08-01 07:14
17.3: the issue is not as bad anymore. The applications can be redeployed even though the applications are not removed from applications folder. At least the manual step removing the directories is no longer necessary

**Comment by toshihiro-shiino** [comment] 2017-08-03 01:33
> The applications can be redeployed

In our testing, we couldn't redeploy.

```
> asadmin -p 20048 -u fcsmadmin redeploy --name oscm-app-openstack $targetEarFile
remote failure: Error occurred during deployment: Exception while deploying the app [oscm-app-openstack] : Could not find sub module [oscm-app-common.war] as defined in application.xml. Please see server.log for more details.
Command redeploy failed.
```

**Comment by kwodzynski** [comment] 2017-08-03 06:05
I have tried redeploy application via GUI of Glassfish. I also could not do this without error.

**Comment by toshihiro-shiino** [comment] 2017-08-03 06:13
While I upgraded OSCM from v17.2 to v17.3, I got .glassfishStaleFiles when I undepoyed oscm and oscm-portal.
It does not seem to be a problem only for the APP application.

**Comment by GoebelL** [comment] 2017-08-09 16:09
P2 for a workaround needed with glassfish. 
We are about migrating to TomEE, which eventually solves many issues including this one. Furthermore we focus to provide OSCM updates full stacked in containers, replacing this manual redeployment.  Upgrade to The Payara server as proposed above maybe an interesting alternative for the community. However most OSCM operators are using glassfish for now. Therefore we should provide some hint how to overcome this issue there.

**Comment by GoebelL** [comment] 2017-09-21 08:55
This issue is not on OSCM applications but on glassfish. Workaround for manual deployment is either to remove the stale files folder manually or use payara. For upcoming releases we focus on TomEE and  container-based deployment of OSCM.

**Closed by GoebelL** 2017-09-21 08:55 UTC
Labels: bug/status/wontfix, foundby/FT, priority/P2, severity/normal
