### ISSUE TITLE
"VMWare controller:" Suspension (Error) email has no Blanks after "Full Stop" (.) characters.

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#187] opened 2016-07-07 08:42 UTC
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
The email which is sent when a subscription is suspended because of error does not have white spaces after the full stop character (.)
[Steps to reproduce]
Create instances until the system does not have any memory left and error occurs when creating a new instance.
Check the suspension email.
[Expected result]
Blank character after full stop  
[Observed result] 
Please se the content of the email below:

Dear user,
The current operation on subscription 'VMware_Original_With_ALL' for customer 'd5b8f512' has been suspended (Instance: '1467876109659').

Reported problem: Insufficient disk space on datastore ''.Failed to extend swap file from 0 KB to 33554432 KB.Could not power on VM : @&!*@*@(msg.vmk.status.VMK_NO_SPACE)No space left on device. Failed to power on VM.An error was received from the ESX host while powering on VM Freddy-000053.
To continue automatic processing, please click the following URL:

[Details]
See above; 

[Messages and logs]

**Comment by GoebelL** [comment] 2016-07-07 10:54
I suspect that this can be changed. Error messages returned from the hypervisor or other 3rd party service, will be included in details sections of APP mail notifications as they are. 
I suggest to first verify whether the message is composed in OSCM. Then check the mail template where it's applied. If the cause is not on the VMWare controller or APP I consider this issue not valid.

**Comment by StavrevaS** [comment] 2016-07-12 07:28
The message in reported problem comes from the vSphere system. The issue is invalid for OSCM.

**Closed by StavrevaS** 2016-07-12 07:28 UTC
Labels: bug/status/invalid, foundby/FT, severity/minor
