### ISSUE TITLE
SSO related issue for multiple CT-MG SOAP webservice clients running in same domain

### ISSUE THREAD

**Issue by skulle** [servicecatalog/development#541] opened 2017-01-18 10:13 UTC
## Condition
- CT-MG installed in **SAML_SP** authentication mode
- Webservices are secured with WSIT
- Installation based on JDK 7 update **>45**
- At least two CT-MG SOAP webservice clients running in the **same domain**, e.g. APP domain

## Effect
One client can make webservice calls to CT-MG, the other one can't! Depends purely on **execution order** of webservice calls. Restart the domain and change the execution order to test the second scenario.

WSIT related stacktraces can be found in server log files on STS, CT-MG and client side. E.g. on STS side:

```
[#|2016-11-24T16:36:49.324+0100|SEVERE|glassfish3.1.2|com.sun.xml.wss.logging.impl.opt.crypto|_ThreadID=163;_ThreadName=Thread-2;|WSS1925: No CipherValue found in CipherData|#]

[#|2016-11-24T16:36:49.327+0100|SEVERE|glassfish3.1.2|com.sun.xml.wss.jaxws.impl|_ThreadID=163;_ThreadName=Thread-2;|WSSTUBE0025: Error in Verifying Security in the Inbound Message.
com.sun.xml.wss.impl.WssSoapFaultException: Invalid Security Header
	at com.sun.xml.ws.security.opt.impl.util.SOAPUtil.newSOAPFaultException(SOAPUtil.java:159)
	at com.sun.xml.ws.security.opt.impl.incoming.processor.CipherDataProcessor.readAsBytes(CipherDataProcessor.java:205)
	at com.sun.xml.ws.security.opt.impl.incoming.EncryptedKey.process(EncryptedKey.java:228)
	at com.sun.xml.ws.security.opt.impl.incoming.EncryptedKey.<init>(EncryptedKey.java:124)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.handleSecurityHeader(SecurityRecipient.java:438)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.cacheHeaders(SecurityRecipient.java:291)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.validateMessage(SecurityRecipient.java:241)
	at com.sun.xml.wss.jaxws.impl.SecurityTubeBase.verifyInboundMessage(SecurityTubeBase.java:450)
	at com.sun.xml.wss.jaxws.impl.SecurityServerTube.processRequest(SecurityServerTube.java:295)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:961)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:910)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:873)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:775)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:386)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:640)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:263)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.invokeAsync(ServletAdapter.java:218)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:159)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:194)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:745)
|#]
```

This behavior was verified with:
- APP (simply login into APP UI) and integrationhelper.war (included in oscm-integration-pack.zip)
- Discovery tool (third party application, CT-MG client) and APP

## Solutions
- Use per client application a separate domain (any JDK version?)
- Use JDK7 update 45 for domains running multiple CT-MG client applications
- Possible other solutions?
  - Glassfish 4, JavaEE 7, JDK 8?
  - Workaround on client application?

**Comment by GoebelL** [comment] 2017-01-23 08:46
Second solution seems most reasonable. If proofed that the solution works, we 'll propose this, as it's also in-line with the JDK recommendation in the OSCM installation guide.

Action items:
* Implement a test scenario to reproduce the reported problem
* Test same on 7u45 to verify the solution 
* Test the scenario in Glassfish 4 and JDK 8_u60, as soon as a stable development version is 
   available.

**Comment by grubskim** [comment] 2017-01-25 16:53
I can confirm this issue with Java version 7.67. Making a webservice call from one client blocks the other. When making a call from the other client, i get the exact same error as in the stacktrace above. 

Tested with:
1) APP login call
2) Integrationhelper "Test web service call to Catalog Manager"

Fails both ways.

This scenario works fine in Java 7.45.

**Comment by GoebelL** [comment] 2017-01-26 08:43
Please also test with JDK 8 on the Glassfish4 branch.

**Comment by grubskim** [comment] 2017-01-31 11:37
Tested with JDK 8u111:
The issue can be reproduced with results similar to JDK > 7.45.

In both scenarios (APP first, Integrationhelper second and vice versa) we get the following stack trace in APP domain server.log:

``
[2017-01-31T12:29:48.552+0100] [glassfish 4.1] [SEVERE] [] [com.sun.xml.wss.jaxws.impl] [tid: _ThreadID=26 _ThreadName=http-listener-1(1)] [timeMillis: 1485862188552] [levelValue: 1000] [[
  WSSTUBE0025: Error in Verifying Security in the Inbound Message.
com.sun.xml.wss.XWSSecurityException: WSS1816: Error occurred while resolving KeyIdentifier
	at com.sun.xml.ws.security.opt.impl.incoming.processor.SecurityTokenProcessor.processKeyIdentifier(SecurityTokenProcessor.java:446)
	at com.sun.xml.ws.security.opt.impl.incoming.processor.SecurityTokenProcessor.resolveReference(SecurityTokenProcessor.java:147)
	at com.sun.xml.ws.security.opt.impl.incoming.processor.KeyInfoProcessor.processKeyInfo(KeyInfoProcessor.java:152)
	at com.sun.xml.ws.security.opt.impl.incoming.processor.KeyInfoProcessor.getKey(KeyInfoProcessor.java:132)
	at com.sun.xml.ws.security.opt.impl.incoming.EncryptedKey.process(EncryptedKey.java:208)
	at com.sun.xml.ws.security.opt.impl.incoming.EncryptedKey.<init>(EncryptedKey.java:124)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.handleSecurityHeader(SecurityRecipient.java:469)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.cacheHeaders(SecurityRecipient.java:316)
	at com.sun.xml.ws.security.opt.impl.incoming.SecurityRecipient.validateMessage(SecurityRecipient.java:265)
	at com.sun.xml.wss.jaxws.impl.SecurityTubeBase.verifyInboundMessage(SecurityTubeBase.java:456)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientResponsePacket(SecurityClientTube.java:436)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processResponse(SecurityClientTube.java:364)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1147)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.client.Stub.process(Stub.java:463)
	at com.sun.xml.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:265)
	at com.sun.xml.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:304)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.invokeRST(TrustPluginImpl.java:629)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.process(TrustPluginImpl.java:175)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.getIssuedTokenContext(STSIssuedTokenProviderImpl.java:144)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.issue(STSIssuedTokenProviderImpl.java:74)
	at com.sun.xml.ws.api.security.trust.client.IssuedTokenManager.getIssuedToken(IssuedTokenManager.java:83)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.invokeTrustPlugin(SecurityClientTube.java:686)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientRequestPacket(SecurityClientTube.java:283)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processRequest(SecurityClientTube.java:249)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.client.Stub.process(Stub.java:463)
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:191)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:92)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:161)
	at com.sun.proxy.$Proxy363.getSubscriptionKeysForSessionId(Unknown Source)
	at org.oscm.integrationhelper.BssClient.testWebServiceCall(BssClient.java:226)
	at org.apache.jsp.TestWebService_jsp._jspService(TestWebService_jsp.java:57)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.crypto.KeySelectorException: com.sun.xml.wss.XWSSecurityException: No Matching private key for BWO4Yw1i11q7yKseS9+1qJmyTUM= thumb print identifier found
	at com.sun.xml.ws.security.opt.impl.incoming.KeySelectorImpl.resolveKeyIdentifier(KeySelectorImpl.java:906)
	at com.sun.xml.ws.security.opt.impl.incoming.processor.SecurityTokenProcessor.processKeyIdentifier(SecurityTokenProcessor.java:443)
	... 72 more
Caused by: com.sun.xml.wss.XWSSecurityException: No Matching private key for BWO4Yw1i11q7yKseS9+1qJmyTUM= thumb print identifier found
	at com.sun.xml.wss.impl.misc.DefaultSecurityEnvironmentImpl.getPrivateKey(DefaultSecurityEnvironmentImpl.java:560)
	at com.sun.xml.ws.security.opt.impl.incoming.KeySelectorImpl.resolveKeyIdentifier(KeySelectorImpl.java:785)
	... 73 more
]]
``

**Comment by grubskim** [comment] 2017-02-08 14:36
After some extensive testing, I was not able to find the reason for the security errors with multiple webservice clients on a single domain. 

As a workaround, I can propose using a single ws client on each domain. This scenario was tested and works fine.

**Comment by StavrevaS** [comment] 2017-02-10 08:51
@skulle, @grubskim do you create the domains with one JDK version, and then test with higher JDK version? 
How is the WSIT configured, with one jar file in the APP domain lib directory, or each client application has own configuration?

**Comment by grubskim** [comment] 2017-02-13 13:53
Yes, i tested it as creating the domains from scratch using the specific JDK. I used one wsit in the lib directory.

**Comment by StavrevaS** [comment] 2017-02-13 15:20
@gertipoppel, please document this behavior for Fix6.
In SAML_SP mode with JDK versions higher than JDK7u45, there might be a problem with running more web service clients in the same domain (e.g APP and IntegrationHelper). It is recommended to deploy each client on a separate domain.

**Comment by SuessI** [comment] 2017-02-14 16:12
Added the sentences below to:
- Section "Java and Ant"  - this section is in the Preparations Chapter of the Installation Guide, of APP, and of each of the integration guides (e.g. AWS Integration Guide). The example in the parenthesis varies accordingly.
- Section "Java" under Restrictions in the Release Notes (for Enterprise Edition)

"When operating OSCM in SAML_SP mode with a JDK version higher than version 7, Update 45, we recommend you run each Web service client (e.g. APP and some other client) in a separate domain. Otherwise, problems with Web service calls may occur. "

**Closed** 2017-02-17 08:44 UTC
Labels: bug/status/fixed, priority/P1

**Comment by SylviaDehn** [comment] 2017-02-20 12:11
[Build] 16.1 fix 1 2017/02/17
verified doc
