### ISSUE TITLE
manage access for marketplace does nort work, if there are many customers ( about 1000)

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/development#133] opened 2016-06-17 11:03 UTC
Date: 2016/06/17
 [Test category]: creative Test

[Steps to reproduce]
1.login as marketplace owner
2.goto marketplace-> manage access and define a closed marketplace.
3.click some Organization for access.
4.click save
[Expected result]
operation should not take time than more as a few sec 
 [Observed result]
takes about 10 minutes

After the operation has finished, all customer are clicked on which has a subscription. This is ok, but if I try to remove access for  a customer I get a error massage:
Organization has already been added to the restricted marketplace. see attachment
![capture](https://cloud.githubusercontent.com/assets/15209605/16148930/3dbc5cc8-348d-11e6-9dee-18b39086872a.PNG)

**Comment by kowalczyka** [comment] 2016-06-17 11:20
This is caused by changes for the additional implementation which is not ready yet (I have comitted only some part). Could you please use previous version for testing (from 15/06/2016)?

**Comment by GoebelL** [comment] 2016-06-20 14:52
>Could you please use previous version for testing (from 15/06/2016)?
It's probably more efficient if Elfriede retests after you have finished the additional implementation. Please comment when the build is available.

**Comment by kowalczyka** [comment] 2016-06-22 10:02
Issue can be verified with the build fb_marketplace_access_UNIT (#30)

**Comment by elfriedegoetz** [comment] 2016-06-22 15:40
Date: 2016/06/22
 [Test category]: creative Test

[Steps to reproduce]
 1.login as marketplace owner
 2.goto marketplace-> manage access 
 3.select a marketplace
 4. click  "Authorized customers only" .
 [Expected result]
 all organisation are listed and all customer with a subscription on this marketplace are marked for access. 
 [Observed result]
 all organisation are listed, but no customer are marked for access. If I click save, the operation takes about 10 min. and afterward all customer with subscription are marked.

**Comment by kowalczyka** [comment] 2016-06-23 12:53
I have been investigating the issue and found out that the reason can be not a number of customers but a huge number of subscriptions for this customers.

@Elfriede is that right? How many subscription are there in your database? 

If this is the reason, very important thing is final implementation of assigning organizations for this subscriptions. Should we proceed with this as in [Expected result] - should we just mark them before save?
Current implementation handle subscriptions and related organizations after save, independently to what has been marked from UI. According to [Expected result] we will avoid this and save will be executed only base on what is marked in UI. To improve the perfermomance we must be sure that this is a good aproach. 

Could you please confirm this?

**Comment by GoebelL** [comment] 2016-06-23 14:10
>Could you please confirm this? 
Yes. 
Please show a busy indicator (i.e. sandglass) when switching the “restrict marketplace” checkbox. This feedback is needed for case of huge data.

**Comment by elfriedegoetz** [comment] 2016-06-24 08:18
@Arkadiusz  No this is not right, each customer has only 10 subscription. Did you switch on the DB log file? There you can see the DB-requests. I my finding there are many unnecessary requests, and perhaps an index for marketplaceaccess table is missing.

**Comment by elfriedegoetz** [comment] 2016-06-28 10:51
Date: 2016/06/28
[Test category]: creative Test

[Steps to reproduce]
1.login as marketplace owner
2.goto marketplace-> manage access and define a closed marketplace.
3.click a Organization A to be granted  access, which have NO subscription on this marketplace.
4.click save
5.Now try to  remove this Organization A and remove the click
6.click save
[Expected result]
operation should  finished without warning
[Observed result]
warning will be shown:
Subscriptions exist for at least one of the organizations for which you are revoking the access to the marketplace. These subscriptions will be suspended. Do you want to continue?

**Comment by amlynarczyk** [comment] 2016-06-28 11:54
Are you sure you mentioned a proper person? I've got an email, but I'm not using this project.

**Comment by elfriedegoetz** [comment] 2016-06-28 12:04
sorry

**Comment by elfriedegoetz** [comment] 2016-06-28 12:20
When is this message supposed to appear?
Subscriptions exist for at least one of the organizations for which you are revoking the access to the marketplace. These subscriptions will be suspended. Do you want to continue?

**Comment by elfriedegoetz** [comment] 2016-06-28 12:39
If the message always  appears the text should be changed.

**Comment by kowalczyka** [comment] 2016-06-28 12:47
I will add the check so that warning does not appear when organizations has no subscriptions.

**Comment by kowalczyka** [comment] 2016-06-29 07:12
@Elfriede could you please give a status of the problems you found in the issue?

I have committed the changes for them - the latest version would be:
fb_marketplace_access_UNIT - 39 (2016-06-29 09:00:47)

**Comment by elfriedegoetz** [comment] 2016-06-29 09:06
tested with build from Date: 2016/06/29
issue of Date: 2016/06/17 is ok
issue of Date: 2016/06/22 is ok
issue of Date: 2016/06/28 is ok

therefore I set the status as verified

**Closed** 2016-06-29 09:49 UTC
Labels: bug/status/verified, feature-branch/fb_marketplace_access, priority/P1
