### ISSUE TITLE
APP/AWS installation fails on GL4

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#567] opened 2017-02-08 15:45 UTC
[Version]
16.1 fix5+ 2017/02/06

[How to reproduce]

 1. configure properties files for app according to documentation
 2. execute:
     ant -f build-db.xml initDB
     ant -f build-glassfish.xml SETUP

[Expected result]
app domain is setup and can be started

[Observed result]
error during call to build-glassfish.xml 

deployApplication:
     [echo] asadmin --user admin333 --passwordfile C:\Users\Sdehn\AppData\Local\Temp\4\BES\script1082986597.txt --port 8848 deploy

     [exec] Application deployed with name oscm-app-aws.
     [exec] Command deploy executed successfully.

deployApplication:
     [echo] asadmin --user admin333 --passwordfile C:\Users\Sdehn\AppData\Local\Temp\4\BES\script1082986597.txt --port 8848 deploy

     [exec] Command deploy failed.
     [exec] remote failure: Error occurred during deployment: Exception while preparing the app : [PersistenceUnit: oscm-app] Unab
le to build Hibernate SessionFactory. Please see server.log for more details.
     [exec] Exception while invoking class org.glassfish.persistence.jpa.JPADeployer prepare method : javax.persistence.Persistenc
eException: [PersistenceUnit: oscm-app] Unable to build Hibernate SessionFactory
     [exec] [PersistenceUnit: oscm-app] Unable to build Hibernate SessionFactory

[Details]
server.log:
sett attached file

**Comment by SylviaDehn** [comment] 2017-02-08 15:46
[server.txt](https://github.com/servicecatalog/development/files/761117/server.txt)

**Comment by StavrevaS** [comment] 2017-02-09 09:17
The persistence.xml of the app project is not adapted to JPA 2.1

**Comment by grubskim** [comment] 2017-02-09 10:11
Adapted persistence of APP to JPA 2.1. The other ones (dataservice and auditlog) are okay. Please re-test.

**Comment by SylviaDehn** [comment] 2017-02-27 14:13
[Version] 2017/02/27 problem still occurs

**Comment by DawidCh** [comment] 2017-02-28 06:36
With the same info in logs?

**Comment by SylviaDehn** [comment] 2017-02-28 14:52
yes, same info
: [PersistenceUnit: oscm-app] Unable to build Hibernate SessionFactory
[exec] [PersistenceUnit: oscm-app] Unable to build Hibernate SessionFactory

**Comment by DawidCh** [comment] 2017-03-01 09:54
The issue is related to ess version. The fix has been ported to ess and issue should be fixed now.

**Comment by SylviaDehn** [comment] 2017-03-02 13:35
Installation still does not work. See screenshot below:

**Comment by SylviaDehn** [comment] 2017-03-02 13:37
![appinstall](https://cloud.githubusercontent.com/assets/15086024/23509358/c3226f22-ff55-11e6-896c-9e163b2aafeb.jpg)

**Comment by grubskim** [comment] 2017-03-02 14:29
Fixed with 61d293d, there was a problem after merge.

**Closed by grubskim** 2017-03-02 14:29 UTC
Labels: bug/status/new, feature-branch/fb_glassfish4_upgrade, foundby/FT, severity/major

**Comment by SylviaDehn** [comment] 2017-03-06 13:17
[Version] 16.1 fix6+ 2017/03/06 verified
