### ISSUE TITLE
The status of organization list check boxes' are not kept the same in the "manage access" page.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#189] opened 2016-07-07 09:23 UTC
Date: 2016/07/01 
[Test category]: creative Test

Severity: minor

[Steps to reproduce]
1. Log in as platform operator, go to "manage access" page.
2. Select a marketplace to manage to check "Authorized customers only", make sure there are more than 10 organizations.
3. Check the check-all box, then go to page "2".

[Expected result]
In page 2, the status of check-all box and other organization check box should be the same.

[Observed result]
With IE9 and firefox, in page 2, the checkall box is checked, but other organization check box is not checked. The status are not same.
With chrome it is OK.

![q -20160707172144](https://cloud.githubusercontent.com/assets/15228666/16648615/854811c4-4467-11e6-90ce-149d2f4c731e.png)

**Comment by GoebelL** [comment] 2016-07-07 13:49
Please test this with a later IE version. If still occurring, please check the browser console for java script errors.

**Comment by jiangweiyi** [comment] 2016-07-08 08:00
I used IE10, IE11, Edge browser, the same situation (like the screenshot) still occurred with the three IE browsers.
The version of Firefox is 38.0.1, has the same problem.
And I checked the browser console, no js errors...

**Comment by badziakp** [comment] 2016-07-19 11:02
Hi,

I can't reproduce described problem. I made several test cases on the following browsers:
IE9: 9.0.8112.16421 Update: 9.0.33
IE11: 11.0.9600.18350 Update: 11.0.32
Microsoft Edge: 25.10586.0.0 Microsoft EdgeHTML: 13.10586

@jiangweiyi 
Could you delete all temporary files in your browser and try again?

**Comment by kowalczyka** [comment] 2016-07-20 06:47
Hello,
I think this is duplicate of #166 which has already been resolved.

**Closed** 2016-07-29 07:07 UTC
Labels: bug/status/assigned, bug/status/duplicate, foundby/ST, priority/P2, severity/minor

**Comment by SylviaDehn** [comment] 2016-08-01 13:06
[Build] 2016/08/01 verified
