### ISSUE TITLE
Cannot assign "Technical Provider" role to Supplier

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#695] opened 2017-05-10 10:27 UTC
Build: BES_MASTER_DELIVERY-10252017/04/26
Windows Server 2016
jdk1.8u121
SAML mode

[How to reproduce]
Create new organization with Supplier role
Update the organization - assign Technical Provider role
Login as Supplier

[Expected result]
The organization has the both roles (can create new Technical Service)

[Observed result]
The organization still has only Supplier role (cannot create new Technical Service)

[Details]
Administrator should have possibility to assign TP role to Supplier

**Comment by digitalfishpond** [comment] 2017-07-03 07:43
When administrator adds 'Technology Manager' role to a Supplier which doesn't already have this role, it becomes possible for the Supplier to add the Technology Manager role to him/herself from Account > Manage users > click on own username > check 'Technology Manager'.

This looks like intentional behaviour. Should it be changed?

Thanks @badziakp for help on this.

**Comment by StavrevaS** [comment] 2017-07-04 09:31
Yes, it works as designed. When the platform operator creates the organization with both roles "Supplier" and "Technology Provider", the corresponding user roles are assigned to the user created with the organization. If the "Technology Provider" role is assigned to the organization after its creation, the user must take additional step in assigning appropriate user role (technology manager) to be able to manage technical services on the platform.

**Closed by StavrevaS** 2017-07-04 09:31 UTC
Labels: bug/status/new, foundby/ST, priority/P2
