### ISSUE TITLE
OSCM multi tenancy issue for modify subscription call 

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#891] opened 2018-01-19 14:44 UTC
Hi Team,

We  found one other issue related customer AD account . 

Use case : We are able to modify the subscription first time using UI successfully using customer AD account and we have try to modify second time same subscription it gives error. 

![modifycallerror](https://user-images.githubusercontent.com/22190140/35156036-9c2fda5e-fd55-11e7-85a6-8ebbf8bbdd8d.png)

please find the log file attached 
[server.log](https://github.com/servicecatalog/development/files/1646844/server.log)

**Comment by GoebelL** [comment] 2018-01-20 10:16
@pujarisat 
Please share with us, if you have any further information here

From given log I can hardly make relation with the IdP System used here. Obviously authentication succeeded with this AD account, otherwise first modify operation wouldn't have been possible. However, there is an issue with repeated subscruption modification in 17.4  (issue is tbd). 

We are working on it.

**Comment by GoebelL** [comment] 2018-01-21 14:12
This seems related to issue #893

**Comment by pujarisat** [comment] 2018-01-22 07:28
Hi Team ,

I have shared all domain log in email and let us know if anything more info need from our end .

-Thanks 
Satling

**Comment by StavrevaS** [comment] 2018-01-22 13:44
This is multitenancy problem. There are 2 tenants in the test environment, the default one and a customer tenant. How to reproduce:

1. Login to marketplace as a customet tenant user;
2. Subscribe to service (the customer admit is set automatically as subscription owner);
3. After the subscription is in active state (green, ready), modify the parameters;
4. After the subscription is in active state (green, ready), modify the parameters again;

The second modification ends with OperationFailedException. 

Just short explanation how the asynchronous subscription modification is working. Before the provisioning call to APP, the subscription configuration to be modified (parameters, unit, owner, id..) is temporary saved to a separate db table (modifiedentity).  If APP reports a successful modification, the new configuration is written into the subscription and the temporary records are deleted. In failure case, the temporary records do need need to be applied and are deleted. So in any case after the asyncronous provisioning is finished, there should be no records in "modifiedentity" table for this subscription.

The error situation is the following:
- One of the temporary records about subscription configuration is about the subcription owner. This is a user from the customer tenant. APP is operated by the platform operator and belongs to the default tenant. It uses a user from the default tenant for the callbacks (SubscriptionService, complete or abort the modification). 
- The server.log shows that the second modification finds temporary records in the "modifiedentity" table for this subscription (we have inconsistent state, they should be deleted after the first modification is finished). APP log shows successful modification and wants to complete the provisioning. In the SubscriptionService.completeAsyncModifySubscription() stack, there is a method call which applies the new configuration to the subscription and then deletes the temporary records - ModifyAndUpgradeSubscriotionBean.updateSubscriptionAttributesForAsyncUpdate(). The subscription owner in the temporary records is the original one from the customer tenant. The method tries to find this user into the tenant of the current user performing the SubscriptionService method call and this is the APP user from default tenant.  So we have a user search where we try to find a user from the customer tenant into the default tenant. As a result ObjectNotFoundException is thrwon, but it does not rollback the transaction. So the subscription will go into the active (ready) state, but the temporary records of the first modification are not deleted.
- The second modification will find inconsistent state in the database - NonUniqueBusinessKeyException for the "modifyentity" record. NPE is thrown since there is no appropriate entry for ModifyEntity.java entity for such case (DataServiceBean.java, DomainObjectException.ClassEnum class2Enum() method)


So the following problems should be fixed:
1.  Avoid NPE in case of NonUniqueBusinessKeyException for ModifyEntity domain object;
2. Search the subscription owner into the tenant of the customer organization to which the subscription belongs.
3. Consider transaction rollback in cases where the subscription can be left in inconsistent state otherwise.

**Comment by StavrevaS** [comment] 2018-01-23 12:58
The issue is fixed with searching the owner (user) in the tenant of the customer organization which owns the subscription.

**Closed by StavrevaS** 2018-01-23 12:58 UTC
Labels: priority/P1

**Comment by GoebelL** [comment] 2018-01-24 08:49
@SylviaDehn 
Please verify with last unit build

**Comment by SylviaDehn** [comment] 2018-01-29 12:32
[Build] 17.3.1 verified in multi-tenant environment
