### ISSUE TITLE
markeplace link forwards to incorrect idp

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#389] opened 2016-10-20 13:36 UTC
Date:2016/10/19

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
2. administrator (platform) uses IDP1, creates organization Org1 (tech provider and supplier), Org1Admin
which is in IDP2
3. administrator creates marketplace M1, M2 and owner is set as Org1, and marketplaces are in IDP2
4. log in as Org1Admin with http://estsdehn.intern.est.fujitsu.com:8180/oscm-portal/?tenantID=IDP
5. work in portal only and publish a service to M1 (I do not switch to marketplace)
6. create Customer organization in IDP2 (customer admin id already exists in IDP2) and assign M1
7. logout
8. customer receives mail with marketplace link
9. customer presses on link, and is brought to M1 
e.g. http://estsdehn.intern.est.fujitsu.com:8180/oscm-portal/marketplace?mId=a8b9eb74
10. customer presses login

[Expected result]
customer is forwarded to IDP2 (which is defined for M1)

[Observed result]
customer is forwarded to IDP1 (default IDP)

[Details]
Blocker because customer cannot log in at marketplace

**Comment by StavrevaS** [comment] 2016-10-20 14:37
If we use directly the marketplace link, without going to the administration portal previously, the user is redirected to the default tenant IDP, not the one from the marketplace.

@DawidCh, as we've discussed, the tenantID is expected in the SessionBean for the marketplace access. If it is empty, it is taken from the http session. The AuthorizationFilter saves tenantID in the http session.  During the debugging, I can notice that the direct request of the marketplace URL does not hit the code, where the tenantID is saved in the http session. So the SessionBean will find an empty tenantID and set the default one.

**Comment by GoebelL** [comment] 2016-10-21 09:18
@DawidCh 
Please improve the spelling of added message in
/oscm-portal/javares/org/oscm/ui/resources/Messages_de.properties, f.e. 
error.tenant.marketplaceRemoved=The selected marketplace doesn''t exist anymore.

Pass to @misako0927 for Japanese translation.

**Comment by DawidCh** [comment] 2016-10-26 05:36
[Details of fix]
The bug was caused by issue with registering customer process. Tenant was not assigned to customer's organization during that process. All the customers were assigned to the same (default) tenant.
Code has been adapted and tenant is being assigned to the customer's organization.

**Closed by DawidCh** 2016-10-26 05:36 UTC
Labels: bug/status/fixed, foundby/FT, pre-release/multitenancy, priority/P1, severity/blocker

**Comment by SylviaDehn** [comment] 2016-10-27 06:43
verified with Build 24.10.2016
