### ISSUE TITLE
cannot assign user to unit for customer associated with non default IDP 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#400] opened 2016-10-24 09:43 UTC
Date:2016/10/23 (multiple IDPs)

[Steps to reproduce]
1. IDPs IDP1(used as default), and IDP2 exist
2. customer org is assigned to IDP2
3. as customer org admin create unit and assign yourself to unit

[Expected result]
customer admin is assigned to unit

[Observed result]
The user ID "ChocolateCookie" does not exist.

[Details]
This works for the default tenant but not for any other tenant. This makes me think that the unit tests (all)
should be also executed not only for default tenant but also for another tenant other than default.

**Comment by StavrevaS** [comment] 2016-10-24 09:49
This is a problem how the data service access the platform user objects. The information about tenant is missing.

**Comment by badziakp** [comment] 2016-10-26 19:10
[similar cases]
1. login as Platform Operator
2. create tenant1
3. create organization userid = supplier without selecting any tenant
4. create organization with the same userId = supplier and assign it to the tenant1
5. create marketplace for supplier created in step 3.
6. log in as supplier from step 3.
7. go to marketplace
8. go to Account > Users & Units 
9. try to edit supplier

[Observed result]
error message: The data has been modified or deleted in the meantime. Please execute the operation again. is shown

[Expected result]
edit user form is shown

**Comment by DawidCh** [comment] 2016-10-27 05:12
Test UserGroupServiceLocalBeanTest is failing and set as ignored. Check what is wrong, the test of  functionality.

**Comment by GoebelL** [comment] 2016-10-28 18:40
[Details of fix]
Reported issue with unit is tested and correctly fixed.

[Open]
- Edit another user A
- change access rights of A in group B using combobox
- deassign A from that group B
- click save 
=> Error message is shown, that user doesn't exist

[Similar cases]
4 similar cases (as above) have been identified and fixed 
1 similar case has been found in regression testing, which is not yet fixed

The issue is left open for the remaining similar case. A workaround for that exists (todo: describe). 
Since severe issues have been corrected and verified, I reduce the severity to normal.

**Comment by DawidCh** [comment] 2016-11-21 13:22
All the similar cases needs to be tested.

**Comment by DawidCh** [comment] 2016-12-07 08:48
Similar cases have been tested and they are fixed.

**Closed by DawidCh** 2016-12-07 08:48 UTC
Labels: bug/status/assigned, foundby/FT, priority/P1, severity/normal

**Comment by SylviaDehn** [comment] 2016-12-19 10:01
[Build] 16.1 fix4 
verified:
- original problem
- assign roles to unit member of non default tenant
- edit user on marketplace default tenant (scenario above)
- create user on marketplace default tenant (scenario above)
- grant Administrator role to the unit (scenario above)
