### ISSUE TITLE
jms error messages  in bes system.log 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#646] opened 2017-04-04 13:23 UTC
[Version]
16.1 fix6+ 2017/04/03

[How to reproduce]
check bes logfile after e.g. signing in as customer admin and assigning users to subscription

[Expected result]
no errors

[Observed result]
jms erros are logged

[Details]
04/04/2017_15:17:50.274 FSP_INTS-BSS: ERROR: ThreadID __ejb-thread-pool4: TaskQueueServiceBean: 70054: Sending the process-related message to JMS queue failed
org.oscm.internal.types.exception.SaaSSystemException: EXCEPTIONID 1491311870274: com.sun.messaging.jms.JMSException: [SEND_REPLY(9)] [C4036]: A broker error occurred. :[500] [B4403]: Exception on processing produced message PacketReference[20482-192.168.99.1(d9:de:72:e7:e4:d6)-62953-1491311870274][TID=4622482368404448256, null]: Unexpected Broker Exception: [Transaction 4622482368404448256[COMPLETE(4)]: is not in STARTED(1) state]  user=jmsuser, broker=localhost:8176(62604)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:157)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendAllMessages(TaskQueueServiceBean.java:65)
	at sun.reflect.GeneratedMethodAccessor2634.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.messaging.jms.JMSException: [SEND_REPLY(9)] [C4036]: A broker error occurred. :[500] [B4403]: Exception on processing produced message PacketReference[20482-192.168.99.1(d9:de:72:e7:e4:d6)-62953-1491311870274][TID=4622482368404448256, null]: Unexpected Broker Exception: [Transaction 4622482368404448256[COMPLETE(4)]: is not in STARTED(1) state]  user=jmsuser, broker=localhost:8176(62604)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.throwServerErrorException(ProtocolHandler.java:4254)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.checkWriteJMSMessageStatus(ProtocolHandler.java:2076)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.writeJMSMessage(ProtocolHandler.java:2024)
	at com.sun.messaging.jmq.jmsclient.WriteChannel.sendWithFlowControl(WriteChannel.java:171)
	at com.sun.messaging.jmq.jmsclient.WriteChannel.writeJMSMessage(WriteChannel.java:123)
	at com.sun.messaging.jmq.jmsclient.Transaction.send(Transaction.java:521)
	at com.sun.messaging.jmq.jmsclient.SessionImpl.writeJMSMessage(SessionImpl.java:969)
	at com.sun.messaging.jmq.jmsclient.MessageProducerImpl.writeJMSMessage(MessageProducerImpl.java:239)
	at com.sun.messaging.jmq.jmsclient.MessageProducerImpl.writeJMSMessage(MessageProducerImpl.java:216)
	at com.sun.messaging.jmq.jmsclient.MessageProducerImpl._send(MessageProducerImpl.java:742)
	at com.sun.messaging.jmq.jmsclient.MessageProducerImpl.send(MessageProducerImpl.java:705)
	at com.sun.messaging.jmq.jmsclient.QueueSenderImpl.send(QueueSenderImpl.java:103)
	at org.oscm.taskhandling.bean.TaskQueueServiceBean.sendObjectMessage(TaskQueueServiceBean.java:151)
	... 33 more
Caused by: com.sun.messaging.jms.JMSException: [SEND_REPLY(9)] [C4036]: A broker error occurred. :[500] [B4403]: Exception on processing produced message PacketReference[20482-192.168.99.1(d9:de:72:e7:e4:d6)-62953-1491311870274][TID=4622482368404448256, null]: Unexpected Broker Exception: [Transaction 4622482368404448256[COMPLETE(4)]: is not in STARTED(1) state]  user=jmsuser, broker=localhost:8176(62604)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.throwServerErrorException(ProtocolHandler.java:4238)
	... 45 more
04/04/2017_15:17:50.274 FSP_INTS-BSS: ERROR: ThreadID __ejb-thread-pool4: TaskQueueServiceBean: 70248: There are 0 message(s) out of 1 is/are sent successfully: Sent Message #0 Failed ::Handler: org.oscm.taskhandling.operations.SendMailHandler, Payload: org.oscm.taskhandling.payloads.SendMailPayload, Details: ;

**Comment by DawidCh** [comment] 2017-04-06 06:35
Closing as duplicate of #604

**Closed by DawidCh** 2017-04-06 06:35 UTC
Labels: bug/status/duplicate, feature-branch/fb_glassfish4_upgrade, foundby/FT, severity/normal
