### ISSUE TITLE
vmware controller: APP Service instance operation: when parameter too long it gets cut off on "Service instance Details"

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#180] opened 2016-07-05 14:01 UTC
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
Testing vmware adapter; creating a (relatively) long Prefix for the machine name:
01234567890123456789012345678901234567890123456-
creating the instance
checking the parameter in the APP Service instance operation:  "Service instance Details"
the value is displayed but just cut off without indication that the name is in fact longer
[Steps to reproduce]
see above
[Expected result]
Value is correct truncated with trailing ...
[Observed result] 
![image](https://cloud.githubusercontent.com/assets/19411047/16587101/508fd6d2-42c9-11e6-9606-40363c111c3e.png)

[Details]
See above; 

[Messages and logs]

**Comment by StavrevaS** [comment] 2016-07-12 13:25
This is an APP UI problem, not VMWare specific. The instance parameter keys and values have variable length. If the value or key is cut, there is no other chance to see them, except in the database tables. The modal windows which shows the parameter table is changed to be resizible and has both scroll bars: horizontal and vertical. So the use can choose using the scrollbars or resizing in order to see the complete information about the service instance.
The issue is fixed with this [commit](https://github.com/servicecatalog/development/commit/502350bab9b9faa6ff31ab48aeaed935c81d45f4).

**Closed** 2016-07-12 13:26 UTC
Labels: bug/status/fixed, foundby/FT, priority/P2, severity/minor

**Comment by SylviaDehn** [comment] 2016-07-22 14:50
verified 2016/07/22
