### ISSUE TITLE
“VMWare controller:” Root password in clear text in log files

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#193] opened 2016-07-07 12:23 UTC
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
Turn on debug logging in vmware adapter 
Created VmWare instance with optional parameter: 
"Linux Root Paaword"
"URL for retrieving a script that is executed after the VM is created" 
"User identifier for executing the script in the VM"
"User password for executing the script in the VM"
Subscribe to instance
evaluate app-vmware-debug.log
[Steps to reproduce]
see above
[Expected result]
All password fields ij the log file are scrambled with '********'
[Observed result] 
LINUX_ROOT_PWD='sunny'
SCRIPT_USERID='root'
SCRIPT_PWD='sunny'
[Details]
See above; 

[Messages and logs]

debug log showing the passwords in clear text
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG Script execute 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG Script insertServiceParameter Script before patching:
#!/bin/bash
shutdown -h now

[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: LINUX_ROOT_PWD
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. LINUX_ROOT_PWD: sunny
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: DOMAIN_NAME
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. DOMAIN_NAME: sunnyside.up.com
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG DataAccessService getVCenterIdentifier vcenter: estvcenterdev1
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: REQUESTING_USER
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. REQUESTING_USER: Julia@DarkSide.com
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: SCRIPT_URL
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. SCRIPT_URL: http://localhost:28880/test_script.sh
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: SCRIPT_USERID
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. SCRIPT_USERID: root
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: SCRIPT_PWD
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. SCRIPT_PWD: sunny
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NUMBER_OF_NICS
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NUMBER_OF_NICS: 1
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_DNS_SERVER
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_DNS_SERVER: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_DNS_SUFFIX
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_DNS_SUFFIX: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_GATEWAY
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_GATEWAY: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_IP_ADDRESS
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_IP_ADDRESS: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_NETWORK_ADAPTER
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_NETWORK_ADAPTER: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: NIC1_SUBNET_MASK
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. NIC1_SUBNET_MASK: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: DATA_DISK_TARGET_1
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. DATA_DISK_TARGET_1: /data
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting parameter: DATA_DISK_SIZE_1
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG ServiceParamRetrieval getServiceSetting found parameter in parameter list. DATA_DISK_SIZE_1: 
[2016-07-07 13:57:23] [__ejb-thread-pool4] DEBUG Script insertServiceParameter Patched script:
#!/bin/bash
LINUX_ROOT_PWD='sunny'
DOMAIN_NAME='sunnyside.up.com'
INSTANCENAME='Freddy-000058'
REQUESTING_USER='Julia@DarkSide.com'
SCRIPT_URL='http://localhost:28880/test_script.sh'
SCRIPT_USERID='root'
SCRIPT_PWD='sunny'
NIC1_DNS_SERVER=''
NIC1_DNS_SUFFIX=''
NIC1_GATEWAY=''
NIC1_IP_ADDRESS=''
NIC1_NETWORK_ADAPTER=''
NIC1_SUBNET_MASK=''
DATA_DISK_TARGET_1='/data'
DATA_DISK_SIZE_1=''

shutdown -h now

**Comment by GoebelL** [comment] 2016-07-07 13:15
This is a kind of similar case issue for issue #179.Therefore both should be handled together. I'd expect that when they are stored encrypted, displayed encrypted they should be also be logged encrypted.

**Comment by GoebelL** [comment] 2016-07-07 13:24
Password scrambling may be no applicable, due to the generic handling as string parameter. Therefore, let's consolidate the expectation ... 
[Expected result] 
No clear text passwords are logged

**Comment by kowalczyka** [comment] 2016-07-11 07:38
This issue is a duplicate of #179 and it will be resolved with it.

**Closed** 2016-07-11 10:57 UTC
Labels: bug/status/duplicate, foundby/FT, priority/P1, severity/normal

**Comment by SylviaDehn** [comment] 2016-07-22 13:07
verified 2016/07/22 debug password not in clear text in logfiles
