### ISSUE TITLE
Define for service view might be showed when the "Display" button of Price model

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/development#105] opened 2016-06-01 10:24 UTC
[Version]
16.0.4

[Client IDE]
OS       : Windows7 Pro SP1
Browser : Google Chrome(50.0.2661.102 m)

[Reproduce frequency]
not always

[How to reproduce]
1) Login as supplier
2) Open Price model "Define for service" view
3) Click "Display" button 

[Expected result]
Show "external billing information" after clicking  "Display" button 
[Observed result]
Define for service view is showed after clicking "Display" button
[Detail]
It sometimes happens. It is easy to happen after clicking  the button continuously.

[Message and logs]
nothing

**Comment by GoebelL** [comment] 2016-06-01 10:26
This bug will be addressed for 16.0.6. Please  check.

**Comment by kowalczyka** [comment] 2016-06-03 11:54
I am unable to reproduce it.

Clicking "Display" opens new tab in the browser with external price model so I am unable to click the "Display" button continuously.

**Comment by GoebelL** [comment] 2016-06-13 11:59
I guess here was some misunderstanding about the meaning of "clicking the button continuously".

Now we've got some details about how to reproduce.

[How to reproduce]
1) Login as supplier
2) Open Price model "Define for service" view
3) Click "Display" button 
     => Price model PDF displays in separate browser tab 
4) Close tab with price model. 
5) In first tab showing "Define for service", click "Display" once again.

[Expected result]
Again separate tab is opened showing same price model PDF.
[Observed result]
Define for service view is shown.

**Comment by kowalczyka** [comment] 2016-07-06 08:11
The issue is not reproducable when following only the step described in [How to reproduce].

The only case which can cause situation similar to [Observed result] is when you additionally open another tab in the same browser with any OSCM site. Then the JSF context is lost in previous tab and the display button no more open a new tab. 

This is is caused by configuration option which setting the context parameter with number of logical views to 1. Such a situation will occur in every place in OSCM where action opening new tab is invoked.

**Comment by redmond2683** [comment] 2016-07-06 13:49
I could reproduce this with Chrome by taking the following steps:

1. Prepare for a service which a price model is not yet imported to
2. Go to the Define for service page
3. Select the service which was prepared for in the step 1
4. Click the Import button
5. Click the Display button
=> Price model PDF displays in separate browser tab
6. Close the tab where the price model is showing
7. Repeat the step 5 and the step 6 till this occurs

It occurs only occasionally in my environment. It seems like this happens when servicePriceModel is initialized before response complete.

**Comment by grubskim** [comment] 2016-08-08 11:17
> The only case which can cause situation similar to [Observed result] is when you additionally open another tab in the same browser with any OSCM site. Then the JSF context is lost in previous tab and the display button no more open a new tab. 

I have just tested it and as per Arkadiusz's comment, it is related to the number of logical views set to 1. Bug can be reproduced by clicking with the middle mouse button (on the Display button or any other link), then switching to the original tab and clicking on the Display button.

The JSF view from the first tab is already invalid. This issue cannot be fixed when the number of logical views is set to 1.

This problem applies not only to this particular button, but to all links in the portal. Please consider adapting the documentation, so it informs that the middle button, as well as CTRL + click are not supported.

**Comment by StavrevaS** [comment] 2016-08-08 14:09
We have the following situation:

- Number of JSF logical views is limited to 1 because of fujitsu jdk (based on Java 1.7_03).
- Increasing the JSF logical views solves the problem.

We tested a solution with displaying the price model in the same window and than going back with the browser back button to the OSCM page. This approach opens other problems.

The issue will be fixed with documenting restriction in release notes. 
It is already documented that the OSCM does not support more than 1 window (tab) from the same browser. In some cases like displaying external price model, the applications opens automatically new window to display some content. Clicking a link in the original window (tab) may not work properly. If the user experiences such problems, it must refresh the content of the first window (tab). 

Alternatively, the oscm-portal.war application can be configured to work with more than one logical view - change value of parameter com.sun.faces.numberOfViewsInSession parameter in the web.xml. This option is not thoroughly tested.

**Comment by gertipoppel** [comment] 2016-08-09 08:51
Added a respective section to the release notes. 
Modified source file: 
DocSources/en/ReleaseNotes/Restrictions/c_Restrictions.xml

**Closed** 2016-08-09 09:04 UTC
Labels: bug/status/fixed, priority/P2, severity/trivial

**Comment by SylviaDehn** [comment] 2016-08-11 09:21
[Build] 2016/08/10 doc issue verified in release note restrictions

**Comment by bogdanbarzu** [comment] 2016-10-24 09:37
Generally, since OSCM is intended as a community-driven open source project, we should configure OSCM per default to work for the community. 
In this case it's much more probable that users/contributors would try out OSCM using the usual JDK, rather than using the Fujitsu JDK. So in my understanding we should configure OSCM per default to support multiple JSF logical views, to offer a good experience with OSCM.
Fujitsu will need to configure it's OSCM commercial distribution accordingly, if shipping it with the Fujitsu JDK.

**Comment by DawidCh** [comment] 2016-10-24 09:55
In further releases of JDK the problem is fixed, so when we upgrade project to Java8 (java EE7) issue will be solved automatically. It will be soon, as gl4 upgrade user story is already waiting for us in backlog (issue #309)
