### ISSUE TITLE
ProvisioningService.modifySubscription() does not deliver subscription attributes

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#490] opened 2016-12-12 10:43 UTC
[Build] 16.1 fix3 01.12.2016

[Steps to reproduce]
1.  create custom subscription and customer attributes as supplier
2. publish mock product service as supplier
3. as customer subscribe to service
4. set subscription attributes when provisioning
5. update subscription attributes

[Expected result]
Check the mockproduct for the new parameters (after provisioning and update); The call "ProvisioningService.modifySubscription" should be be used to get the new subscription (service)  attributes.

[Observed result]
Subscription (Service) attributes cannot be received, only the customer attributes.

**Comment by GoebelL** [comment] 2016-12-12 12:24
@MiethanerR 
Please check against RQs if this issue is valid. The subscription attributes are saved before by ProvisioningService.saveAttributes, while ProvisioningService.modifySubscription handles customer attributes. That's a matter of definition - not necessarily a bug. However the javadoc doesn't mention about it. Thus, the only issue I can see right now is to improve the documentation. Please check this.

**Comment by MiethanerR** [comment] 2016-12-12 12:45
@GoebelL The issue is valid. I fixed it before in the feature branch but somehow this wasn't merged into master.

**Comment by MiethanerR** [comment] 2016-12-12 15:22
I fixed the filter call for the UDAs in the service. The provision call contains now always the current subscription UDAs like intended. I also reformulated the comments for the interface to be more clear.

**Closed by MiethanerR** 2016-12-12 15:22 UTC
Labels: bug/status/fixed, foundby/FT, priority/P1, severity/major

**Comment by SylviaDehn** [comment] 2016-12-16 11:03
verified, but the problem now is that the modifySubscription is not called if only the subscription attributes are updated. New issue for this is https://github.com/servicecatalog/development/issues/507
