### ISSUE TITLE
Cannot subscribe to the example service when running the OSCM Docker container

### ISSUE THREAD

**Issue by bogdanbarzu** [servicecatalog/development#234] opened 2016-07-20 09:26 UTC
I just run the newest OSCM Docker container from Dockerhub and I cannot subscribe to the test services in the marketplace. I get an error saying that the technical service the marketplace offerings are based upon is not running.

Presumable cause: as I see in the output of the docker run command, the master-indexer-domain and the bes-domain Glassfish domains are started, but not the example-domain (where the example/mock service runs). For an inexperienced OSCM user though this would not be obvious, preventing her/him to test the capabilities of OSCM, as the Docker container is intended for - from this point of view I rather consider this issue as major.

Could somebody please check and fix the Docker container on Dockerhub?

**Comment by bogdanbarzu** [comment] 2016-07-20 10:22
If the wrong ports issue is priority/P1, than also this one is P1. Because to subscribe on a service is a key function of a service catalog/marketplace. For the ports, there is a workaround, to configure them correctly. But starting the example-domain is not so straight forward.

**Comment by GoebelL** [comment] 2016-07-20 10:26
I agree. Will be fixed asap.

**Comment by kowalczyka** [comment] 2016-07-21 10:05
OSCM docker image is not using the example domain for mock service. It is deployed on the bes-domain.

I have just finished investigation of the problem with subscribing to service. It was caused by technical service definition which is imported with playground dataset during building the image. I have updated it with proper values.

**Comment by bogdanbarzu** [comment] 2016-07-22 08:41
Ok, I understand the cause.

Could you please tell me: have you updated it only in the source code? Or did you also uploaded a new & fixed Docker container on Dockerhub?

**Comment by kowalczyka** [comment] 2016-07-25 05:46
I have just updated the source code. Building and uploading of the Docker image is done by Jenkins.

**Closed** 2016-07-25 05:52 UTC
Labels: bug/status/fixed, priority/P1, severity/major

**Comment by GoebelL** [comment] 2016-07-28 12:58
Before, please check #256. Maybe is duplicate.
